### PR TITLE
Refine the permission system

### PR DESCRIPTION
**Pull request by alecslupu**

### CODE REVIEW

**Review by microstudi — DISMISSED** [review]
This is ok.
 A note for the future: 
- [ ] Add a permissions spec

**Comment by alecslupu** [comment]
@microstudi I will have a look on this later

**Comment by microstudi** [comment]
We will create a task to add missing specs, I prefer to merge all of this first  to avoid stalling and too much conflicts

**Comment by alecslupu** [comment]
> We will create a task to add missing specs, I prefer to merge all of this first to avoid stalling and too much conflicts

keeping them for a long time , makes the development process hard as well, due to Db migrations and dependencies.

**Pull request merged**
